---

stages:
  - validate
  - build

validate:
  stage: validate
  tags:
    - packer
  script:
    - packer validate main.json

build:
  stage: build
  tags:
    - packer
  script:
    - '[[ "$(git tag | tail -1)" != "" ]] && packer build -var version="$(git tag | tail -1)" main.json || packer build main.json'
  when: manual
